api/urls.py
# --*-- encoding: utf-8 --*--
from django.conf.urls import url
from rest_framework import routers
import views

router = routers.DefaultRouter()
router.register(r'users', views.UsersAPI)
router.register(r'addresses', views.AddressAPI)
router.register(r'medias', views.MediasAPI)

urlpatterns = router.urls
api_login_pattern = url(r'login/$', views.login, name='api-login')
urlpatterns.append(api_login_pattern)

profiles/urls.py
from django.conf.urls import url
import views


app_name = "profiles"
urlpatterns = [
    url(r'^$', views.users, name="full_list"),
    url(r'users_lst/$', views.UsersListView.as_view(), name='simple_lst'),
    url(r'details/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'new/$', views.UsersCreateView.as_view(), name='new'),
]

registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework import routers
import views  # import our custom sign in view to also ask for an email

urlpatterns = [
    url('accounts/', include('django.contrib.auth.urls')),
    url(r'^home/', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('profiles.urls')),
    url(r'^$', auth_views.login, name='login'),
    url(r'^register/', views.signup, name='register'),  # use our custom view
    url(r'^logout/', auth_views.logout, name='logout'),

    url(r'^api/', include('api.urls')),
    #url(r'^api/v2/', include('api.urls2')),
]

profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from .validators import (validate_first_name, validate_last_name, validate_email, validate_timezone,
                         validate_city, validate_state, validate_country)


class Gender(models.Model):
    """
    A class representing a gender.
    """

    GENDER_OPTIONS = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    gender = models.CharField(
        max_length=6,
        choices=GENDER_OPTIONS,
        default='Male',
        null=True,
        blank=True,
    )

    def __unicode__(self):
        return self.gender

    class Meta:
        abstract = True


class Users(Gender):
    """
    User data model representation.
    """
    first_name = models.CharField(max_length=100, validators=[validate_first_name])
    last_name = models.CharField(max_length=100, validators=[validate_last_name])
    age = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=False, validators=[validate_email])
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    active = models.BooleanField(null=False, blank=False)
    timezone = models.CharField(max_length=50, null=True, blank=True, validators=[validate_timezone])

    def __unicode__(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    class Meta:
        verbose_name_plural = 'Users'


class Medias(models.Model):
    """
    Social media model.
    """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    url = models.URLField()
    user_id = models.ForeignKey('Users', on_delete=models.CASCADE, related_name='socials')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Medias'


class Address(models.Model):
    """
    A class representing an address.
    """
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='address')
    address = models.TextField(max_length=100, null=False, blank=False)
    city = models.CharField(max_length=50, null=True, blank=True, validators=[validate_city])
    state = models.CharField(max_length=50, null=True, blank=True, validators=[validate_state])
    country = models.CharField(max_length=50, null=True, blank=True, validators=[validate_country])
    zip_code = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return self.address

    class Meta:
        verbose_name_plural = 'Addresses'

profiles/forms.py
from .models import Users, Address
from django import forms


class AddressForm(forms.ModelForm):
    """
    A simple form for Address class.
    """
    class Meta:
        model = Address
        fields = [
            'address',
            'city',
            'state',
            'country',
            'zip_code',
        ]
        labels = {
            'address': 'Address',
            "city": "City",
            "state": "State",
            "country": "Country",
            "zip_code": "Zip Code",
        }


class UsersForm(forms.ModelForm):
    """
    A form for the Users model.
    """
    class Meta:
        model = Users

        fields = [
            "first_name",
            "last_name",
            "age",
            "gender",
            "email",
            "phone_number",
            "active",
            "timezone",
        ]

        labels = {
           "first_name": "First Name",
           "last_name": "Last Name",
           "age": "Age",
           "gender": "Gender",
           "email": "Email",
           "phone_number": "Phone Number",
           "active": "Active",
           "timezone": "Time Zone",
        }

profiles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import TemplateView, DetailView, ListView, CreateView
from django.urls.base import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
from .models import Users
from .forms import UsersForm, AddressForm


@login_required
def users(request):
    """
    List all the users stored in the database.
    """
    users_lst = Users.objects.all()
    return render(request, 'profiles/users.html', {'users_lst': users_lst})


# This is what the exercise asked for, however,
# I used the UsersListView(ListView) instead.
# If you want to use it, just UserListView by UsersView
# in the urls.py of this django app (profiles)
@method_decorator(login_required, name='dispatch')
class UsersView(TemplateView):
    """
    Shows all the users and their addresses.
    """
    template_name = 'profiles/users_lst.html'

    def get_context_data(self, **kwargs):
        users = Users.objects.all()
        context = {'object_list': users}
        return context


@method_decorator(login_required, name='dispatch')
class UsersListView(ListView):
    """
    A class to list all the users.
    """
    model = Users
    template_name = 'profiles/users_lst.html'


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    """
    Show the user details.
    """
    model = Users
    template_name = 'profiles/details.html'


@method_decorator(login_required, name='dispatch')
class UsersCreateView(CreateView):
    """
    A view to create a new user.
    """
    model = Users
    template_name = 'profiles/new.html'
    success_url = reverse_lazy("profiles:new")

    form_class = UsersForm
    second_form_class = AddressForm

    def get_context_data(self, **kwargs):
        context = super(UsersCreateView, self).get_context_data(**kwargs)
        if 'users_form' not in context:
            context['users_form'] = self.form_class(self.request.GET)
        if 'address_form' not in context:
            context['address_form'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, **kwargs):
        self.object = self.get_object
        users_form = self.form_class(request.POST)
        address_form = self.second_form_class(request.POST)
        if users_form.is_valid() and address_form.is_valid():
            new_address = address_form.save(commit=False)
            new_address.user_id = users_form.save()         # Assign the foreign key to the address record
            new_address.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(context={'users_form': users_form,
                                                    'address_form': address_form})

profiles/templates/profiles/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Details - {{ object }}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-3">Details for user: {{ object }}</h1>

    <table class="table table-sm mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Email</th>
                <th>Active</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Country</th>
                <th>Zip Code</th>
                <th>Time Zone</th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.first_name }}</td>
            <td>{{ object.last_name }}</td>
            <td>
                {% if object.age %}
                {{ object.age }}
                {% endif %}
            </td>
            <td>
                {% if object.gender %}
                {{ object.gender }}
                {% endif %}
            </td>
            <td>{{ object.email }}</td>
            <td>{{ object.active }}</td>
            <td><ul>
                {% for address in object.address.all %}
                    {% if address.address %}
                        <li>{{ address.address }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in object.address.all %}
                    {% if address.city %}
                        <li>{{ address.city }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in object.address.all %}
                    {% if address.state %}
                    <li>{{ address.state }}</li>
                {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in object.address.all %}
                    {% if address.country %}
                        <li>{{ address.country }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in object.address.all %}
                    {% if address.zip_code %}
                        <li>{{ address.zip_code }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td>
                {% if object.age %}
                {{ object.timezone }}
                {% endif %}
            </td>

        </tr>
        </tbody>
    </table>
</div>

<link rel="stylesheet" href="{% static 'profiles/css/details.css' %}">

<style>
table tr td ul {
    list-style:none;
    padding-left: 0px;

}

.container {
    margin-left: 0px;
}

table tr td ul li {
    white-space: nowrap;
}
</style>

{% endblock content %}

profiles/templates/profiles/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - New{% endblock %}

{% block content %}

<div class="cont">
    <form method="POST" action="">
    <h1 class="mt-3">Add new user</h1>

        {% csrf_token %}
        {{ users_form.as_p }}
        {{ address_form.as_p }}

        <div class="row">
            <input type="submit" class="btn btn-primary col-md-4" value="Submit">
            <div class="col-md-4"></div>
            <input type="button" class="btn btn-danger col-md-4" value="Cancel" onclick=window.location.href="{% url 'profiles:simple_lst' %}";>
        </div>
    </form>

</div>

<link rel="stylesheet" href="{% static 'profiles/css/new.css' %}">

{% endblock %}

profiles/templates/profiles/users.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - Detailed List{% endblock %}

{% block content %}
<div class="container">
    <h1 class="title mt-3">Users</h1>
    <table class="table table-sm mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Email</th>
                <th>Active</th>
                <th>Time Zone</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Country</th>
                <th>Zip Code</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users_lst %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>
                {% if user.age %}
                {{ user.age }}
                {% endif %}
            </td>
            <td>
                {% if user.gender %}
                {{ user.gender }}
                {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.active }}</td>

            <td>
                {% if user.timezone %}
                {{ user.timezone }}
                    {% endif %}
            </td>
            <td><ul>
                {% for address in user.address.all %}
                    {% if address.address %}
                        <li>{{ address.address }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in user.address.all %}
                    {% if address.city %}
                        <li>{{ address.city }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in user.address.all %}
                    {% if address.state %}
                    <li>{{ address.state }}</li>
                {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in user.address.all %}
                    {% if address.country %}
                        <li>{{ address.country }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>
            <td><ul>
                {% for address in user.address.all %}
                    {% if address.zip_code %}
                        <li>{{ address.zip_code }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<link rel="stylesheet" href="{% static 'profiles/css/users.css' %}">

<style>
table tr td ul {
    list-style:none;
    padding-left: 0px;

}

.container {
    margin-left: 0px;
}

table tr td ul li {
    white-space: nowrap;
}
</style>
{% endblock %}

profiles/templates/profiles/users_lst.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - Simple List{% endblock %}

{% block content %}

<div class="container">

    <div>
        <h1 class="mt-3">Users</h1>
    </div>

<table class="table mt-3">
    <thead>
        <tr>
            <th>User</th>
            <th>Address</th>
            <th>Options</th>
        </tr>
    </thead>
    {% if object_list %}
        {% for user in object_list %}

            <tbody>
                <tr>
                    <td>{{ user }}</td>
                    <td>{% for address in user.address.all %}
                        <ul>
                            <li>{{ address }}</li>
                        </ul>
                        {% endfor %}
                    </td>
                    <td><a href="{% url 'profiles:user_detail' user.id%}">See Details</a></td>
                </tr>
            </tbody>

        {% endfor %}
    {% endif %}
</table>

</div>

<link rel="stylesheet" href="{% static 'profiles/css/users_lst.css' %}">

<style>
table tbody tr td ul {
    list-style: none;
    margin-left: 0px;
    padding-left: 0px;
}
</style>

{% endblock %}